config/routes.rb
Rails.application.routes.draw do
  root "blogs#index"

  get 'sessions/new'
  
  
  resources :blogs
  

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create

    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body, :user_name, :user_id, :image, :remove_img, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  

  
   def new
   end

  
   def create
    user = User.find(params[:id])
    
  end

  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end


   
end

app/controllers/users/confirmations_controller.rb
 frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
   GET /resource/confirmation/new
   def new
     super
   end

   POST /resource/confirmation
   def create
     super
   end

   GET /resource/confirmation?confirmation_token=abcdef
   def show
     super
   end

   protected

   The path used after resending confirmation instructions.
   def after_resending_confirmation_instructions_path_for(resource_name)
     super(resource_name)
   end

   The path used after confirmation.
   def after_confirmation_path_for(resource_name, resource)
     super(resource_name, resource)
   end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

   GET /resource/sign_up
   def new
     super
   end

   POST /resource
   def create
     super
   end

   GET /resource/edit
   def edit
     super
   end

   PUT /resource
   def update
     super
   end

   DELETE /resource
   def destroy
     super
   end

   GET /resource/cancel
   Forces the session data which is usually expired after sign
   in to be expired now. This is useful if the user wants to
   cancel oauth signing in/up in the middle of the process,
   removing all OAuth session data.
   def cancel
     super
   end

   protected

   If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
   end

   If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
   end

   The path used after sign up.
   def after_sign_up_path_for(resource)
     super(resource)
   end

   The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
     super(resource)
   end
end

app/controllers/users/sessions_controller.rb
 frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create]

  GET /users/sign_in
   def new
     super
   end

  POST /users/sign_in
  def create
    super
  end

  DELETE /users/sign_out
   def destroy
     super
   end

  protected

   If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
   end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  #
   def create
     super
   end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
     #@current_user = @current_user || User.find_by(id: session[:user_id])と同じ意味
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end
  def new
  end

  def create
  end



  def destroy
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_fit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blogs/_form.html.haml
= form_with(model: blog, local: true) do |form|
  - if blog.errors.any?
    #error_explanation
      %h2
        = pluralize(blog.errors.count, "error")
        prohibited this blog from being saved:
      %ul
        - blog.errors.full_messages.each do |message|
          %li= message
  
  .wrapper
    .field
      = form.label :title
      = form.text_field :title
    .field
      = form.label :body
      = form.text_area :body
    .field
      = form.label :image
      = form.file_field :image
    .actions
      = form.submit

app/views/blogs/edit.html.haml
%h1 Editing Blog
= render 'form', blog: @blog
= link_to 'Show', @blog
= link_to "消去", "/blogs/#{@blog.id}", method: :delete
= link_to 'Back', blogs_path
  

app/views/blogs/index.html.haml
!!!
%html{:lang => "ja"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %link{:href => "application.css", :rel => "stylesheets"}/
    %title YoshiBlog

  %body
    .header
      .header_title
        %a.title{:href => "/blogs"} YoshiBlog
      %ul.lists
        %li.list
          = link_to "https://twitter.com" do
            = fa_stacked_icon("twitter", base: "square-o", class:"icon")
        %li.list 
          = link_to "新規投稿", new_blog_path, class:"post"
        %li.list 
          = link_to "ログイン", login_path, class:"post"
        %li.list
          = link_to "新規登録", new_user_registration_path, class:"post"

    %main
      .wrapper
        %article
          .article__contents
            - @blogs.each do |blog|
              .article__contents__img
                = image_tag src="#{blog.image}", size: "700x400", class:"picture"
              .article__contents__title 
                title:
                = blog.title
              .article__contents__btn
                .article__contents__btn__edit
                  = link_to 'Edit', edit_blog_path(blog), class:"content__btn"
                .article__contents__btn__show
                  = link_to 'Show', blog_path(blog), class:"content__btn"
              %hr.border
            

app/views/blogs/new.html.haml
%h1 New Blog
= render 'form', blog: @blog
= link_to 'Back', blogs_path

app/views/blogs/show.html.haml
!!!
%html{:lang => "ja"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %link{:href => "application.css", :rel => "stylesheets"}/
    %title YoshiBlog

  %body
    .header
      .header_title
        %a.title{:href => "/blogs"} YoshiBlog
      %ul.lists
        %li.list
          = link_to "https://twitter.com" do
            = fa_stacked_icon("twitter", base: "square-o", class:"icon")
        %li.list 
          = link_to "新規投稿", new_blog_path, class:"post"

    %main
      .wrapper
        %article
          .article__contents
            .article__contents__img
              = image_tag src="#{@blog.image}", size: "700x400", class:"picture"
            .article__contents__title
              = @blog.title
            .article__contents__body
              = @blog.body
            = link_to 'Back', blogs_path
            

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Yoshiblog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield